### PR TITLE
Tesco accounts potential fix WIP

### PR DESCRIPTION
**Pull request by stemount**
This requires thorough testing, lets chat about ways to test this properly

I used

`    $par_data_manager = \Drupal::service('par_data.manager');

    $users = User::loadMultiple();

    foreach (array_slice($users, 200, 10) as $id => $user) {
      var_dump(array_keys($par_data_manager->hasMemberships($user)['par_data_partnership']));
    }
`

to sense check this by checking 10 at a time…

### CODE REVIEW

**Comment by kalpaitch** [comment]
I think this could be potentially dangerous. It would allow any person record discovered on another entity, partnership etc to be included.

**Comment by kalpaitch** [comment]
I think it would be good to find out why this issue is occurring before fixing as this is a potentially troublesome area. What is the difference (in reference links) between the tesco partnership that is showing, and the one that is not.

**Comment by stemount** [comment]
It is worth noting on this issue that https://regulatorydelivery.atlassian.net/browse/PAR-1194 applies as well.

**Comment by kalpaitch** [comment]
True, we potentially need to work this all out before we release members.

**Comment by kalpaitch** [comment]
Closing while further investigation underway.

**Pull request closed without merging**
