### PR TITLE
PAR-998

### PR DESCRIPTION
**Pull request by jon-edery**
Rendering updates for attachments.

Testing instructions:

After checking out the branch.

pages to review in the enforcement journeys:

/enforcement-notice/[ID]/raise/[ID}/confirm 
/enforcement-notice/[ID]/approve
/enforcement-notice/[ID]/reviewed

Ensure the correct markup is being rendered as per other form elements.
Ensure the title attachments is rendered correctly for all pages.

Automated tests to be updated to avoid/indicate code regressions.

screen shot 2017-11-23 at 11 02 02

screen shot 2017-11-23 at 11 01 53

### CODE REVIEW

**Comment by jaffamonkey** [comment]
Created step to upload files so this is checkable feature

**Comment by kalpaitch** [comment]
Ah yes, now I see the relevance of the upload conversations :) :+1:

**Comment by jon-edery** [comment]
Great team work 👍

**Comment by stemount** [comment]
@jon-edery we need the test in this PR still I think cc @jaffamonkey

**Pull request merged**
